version: '2'

services:
  notebook-server:
    image: ziff/notebook:latest
    volumes:
      - $GDRIVE_NOTEBOOKS_DIRECTORY:/home/jovyan/mynotebooks
      - ./Challenges:/home/jovyan/Challenges
      - ./Concepts:/home/jovyan/Concepts
    ports:
      - 8888:8888
    command: sh run.sh
